language: php

php:
  - 5.3

mysql:
  database: drupal7_minimal_behat
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null

install:
  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # install drush
  - pear channel-discover pear.drush.org
  - pear install drush/drush-5.8.0
  - phpenv rehash

before_script:
  # navigate out of module directory to prevent blown stack by recursive module lookup
  # - cd ../..

  # install dependencies managed by composer
  - composer install

  # debugging  
  - ls -l
  - pwd
  # - ls -la vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/
  - ls -la vendor/drupal

  # start with a fresh settings.php for a clean install
  - rm docroot/sites/default/settings.php
  - cp docroot/sites/default/default.settings.php docroot/sites/default/settings.php

  # navigate into docroot, where we're going to install the site
  - cd docroot
  
  # create new site, stubbing sendmail path with true to prevent delivery errors and manually resolving drush path
  - mysql -e 'create database drupal7_minimal_behat'
  - php -d sendmail_path=`which true` `pear config-get php_dir`/drush/drush.php --yes site-install minimal --db-url=mysql://root:@127.0.0.1/drupal7_minimal_behat --account-name=admin --account-pass=admin

  # reference and enable travis_ci_drupal_module_example in build site
  # - ln -s $(readlink -e $(cd -)) drupal7-minimal-behat/drupal/sites/all/modules/travis_ci_drupal_module_example
  # - cd drupal7-minimal-behat/drupal
  # - drush --yes pm-enable travis_ci_drupal_module_example

  # start a web server on port 8080, run in the background; wait for initialization
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

script:
  - cd ..; ./behat;
